#! /bin/sh

if ! rulc -l > /dev/null ; then
    (setsid ruld &)
    while ! rulc -l > /dev/null ; do
        sleep 0.1
    done
fi
rules=$(rulc -l)
if [ -z "$rules" ] ; then
    rulc -a 'class == "Steam"' 'floating = on desktop = ^9'
    rulc -a 'instance == "ncmpcpp"' 'desktop = ^8'
    rulc -a 'class == "Mumble"' 'floating = on'
    rulc -a 'class == "Gimp"' 'floating = on'
    rulc -a 'class == "feh"' 'floating = on'
fi
