#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%A, %B %d, %H:%M %P' > "$PANEL_FIFO" &

case "$flavor" in
	bar)
		cat "$PANEL_FIFO" | panel_bar | bar -g "x18+0+0" -f "-*-gohufont-medium-r-*-*-11-*-*-*-*-*-iso10646-*" -u 2 -B "#FF1d1f21" -F "#FFc5c8c6" &
		;;
esac

wait
