#! /bin/sh

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{F#FF81a2be}${line#?}"
			;;
		T*)
			# xtitle output
			title="%{F#FF707880}${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos%{U#FFde935f}%{F#FF373b41}%{+u} • %{-u}"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos%{U#FFde935f}%{F#FF373b41}%{+u} ○ %{-u}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos%{U#FFde935f}%{F#FFcc6666}%{+u} • %{-u}"
						;;
					o*)
						# inactive but occupied desktop
						wm_infos="$wm_infos%{F#FF707880} • "
						;;
					f*)
						# inactive desktop
						wm_infos="$wm_infos%{F#FF373b41} ○ "
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos %{F#FFcc6666}• "
						;;
					L*)
						layout=""
						wm_infos="$wm_infos %{B#FF1d1f21}%{F#FFc5c8c6}$layout"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l} $title %{c} $wm_infos %{r} $sys_infos "
done
