" Set font and font size
if has("win16") || has("win32") || has('win64')
    set guifont=Consolas:h9
else
    set guifont=Ubuntu\ Mono\ 10
endif

" No toolbar, menu bar, and scroll bar in GVim
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=m
set guioptions-=M
set guioptions-=r
set guioptions-=R
