" --------------------
" Initialize dein
" --------------------
if &compatible
	set nocompatible
endif
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

call dein#begin('~/.vim/dein/')

call dein#add('Shougo/dein.vim')

" NeoComplete requires vim to be compiled with lua support
if has('lua')
	call dein#add('Shougo/neocomplete.vim')
endif
" call dein#add('scrooloose/syntastic', { 'on_ft': 'c,cpp,python,lua,html,css'})

call dein#add('neomake/neomake')

call dein#add('junegunn/fzf', { 'build': './install --all', 'merged': 0})

call dein#add('Rip-Rip/clang_complete', { 'on_ft': 'c,cpp'})
call dein#add('davidhalter/jedi-vim', { 'on_ft': 'python' })
call dein#add('tweekmonster/braceless.vim', { 'on_ft': 'python' })

call dein#add('lervag/vimtex', { 'on_ft': 'tex' })

call dein#add('godlygeek/tabular')
call dein#add('Raimondi/delimitMate')
call dein#add('tomtom/tcomment_vim')
call dein#add('tpope/vim-surround')
call dein#add('tpope/vim-repeat')
call dein#add('morhetz/gruvbox')

call dein#end()

if dein#check_install()
	call dein#install()
endif


" -----------------
" Personal Settings
" -----------------

filetype plugin indent on
syntax on

setglobal fileencoding=utf-8
set encoding=utf-8
set fileencodings=utf-8,euc-jp,sjis
set termencoding=utf-8

" Remap leader key from default backslash(\) to spacebar
let mapleader=" "

" Disable sounds
set noerrorbells
set novisualbell
set t_vb=

" Improves redrawing
set ttyfast

" Don't update screen while executing a macro, register or
" other commands that not have been typed
set lazyredraw

" Mouse
set mouse=a   " Enable Mouse
set mousehide " Hide mouse when typing

" Allows you to edit other files without saving current file
set hidden

" No backup files
set nobackup
set noswapfile

" Number of command lines to remember
set history=1000

" Allow to use backspace in insert mode
set backspace=indent,eol,start

" Adds line numbers to the left side of the editor
set number

" Adds column numbers to the bottom right of the editor
set ruler

" Highlight the line you are on
set cursorline

" Specific tabs, spaces and textwidth for certain file types
autocmd FileType html,css setlocal tabstop=4 softtabstop=4 shiftwidth=4 noexpandtab
autocmd FileType java setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType javascript setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType c setlocal tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab textwidth=80 equalprg=indent\ -kr\ -i8\ -l80
autocmd FileType cpp setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab textwidth=120
autocmd FileType xml setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab

" Show tabs and end of line characters
set list
set listchars=tab:▸\ ,eol:¬

" Add a visual vertical line 1 column after textwidth
if exists('+colorcolumn')
	set colorcolumn=+1
endif

" Searching
set hlsearch   " Highlight search terms
set incsearch  " Show search matches as you type
set ignorecase " Case-Insensitive when searching
set smartcase  " Except if there's a capital letter

" Time it takes to update gui while not doing anything (milliseconds)
set updatetime=200

" Fixes delay after pressing ESC and then O
set timeout timeoutlen=1000 ttimeoutlen=100

" Fixes lag/delay when inserting parentheses and brackets in large files
let g:matchparen_insert_timeout=5

" Color Scheme
set background=dark
colorscheme gruvbox

" Enable command-line completion
set wildmenu
set wildignore+=*.swp,*.bak,*.pyc,*.class,*/.git/**/*,*/.hg/**/*,*/.svn/**/*,*/tmp/*,*.so
set wildignorecase
set wildmode=list:full

" Automatically remove trailing whitespace
" autocmd FileType c,cpp,java,python,lua,vim,html,css autocmd BufWritePre <buffer> :%s/\s\+$//e
autocmd FileType c,cpp,python,lua,vim autocmd BufWritePre <buffer> :%s/\s\+$//e

" Detect markdown files and set the correct filetype
au BufRead,BufNewFile *.md set filetype=markdown

" Map CTRL + L to clear highlighting and then clear/redraw screen.
nnoremap <silent> <C-L> :nohlsearch<CR><C-L>

" -------
" Plugins
" -------

" NeoComplete
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#sources#syntax#min_keyword_length = 3

let g:neocomplete#enable_auto_close_preview = 1

let g:neocomplete#sources#dictionary#dictionaries = { 'default' : '' }
if !exists('g:neocomplete#keyword_patterns')
	let g:neocomplete#keyword_patterns = {}
endif

" Allow only words to be in the keyword
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Enable omni completion
if !exists('g:neocomplete#force_omni_input_patterns')
	let g:neocomplete#force_omni_input_patterns = {}
endif

let g:neocomplete#force_omni_input_patterns.c =
			\ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:neocomplete#force_omni_input_patterns.cpp =
			\ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'

" Allow clang_complete and neocomplete to work together
" let g:neocomplete#force_overwrite_completefunc = 1
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_default_keymappings = 0
" let g:clang_use_library = 1

" Syntastic
" let g:syntastic_c_compiler = 'clang'
" let g:syntastic_cpp_compiler = 'clang++'
" let g:syntastic_cpp_compiler_options = '-std=c++11'

" Neomake
autocmd! BufWritePost * Neomake

" FZF
nnoremap <silent> <c-p> :FZF<CR>

" Jedi
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
let g:neocomplete#force_omni_input_patterns.python =
	\ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

" Vim-tex
if !exists('g:neocomplete#sources#omni#input_patterns')
	let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.tex =
			\ '\v\\%('
			\ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
			\ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
			\ . '|hyperref\s*\[[^]]*'
			\ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
			\ . '|%(include%(only)?|input)\s*\{[^}]*'
			\ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
			\ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
			\ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
			\ . ')'

autocmd FileType python BracelessEnable +indent

let g:tex_flavor='latex'
