" --------------------
" Initialize NeoBundle
" --------------------
if has('vim_starting')
	set nocompatible
	if has("win16") || has("win32") || has("win64")
		set runtimepath+=$VIM/bundle/neobundle.vim/
	else
		set runtimepath+=~/.vim/bundle/neobundle.vim/
	endif
endif

if has("win16") || has("win32") || has("win64")
	call neobundle#rc(expand('$VIM/bundle/'))
else
	call neobundle#rc(expand('~/.vim/bundle/'))
endif

" Let NeoBundle manage NeoBundle
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundleLazy 'scrooloose/syntastic'
	autocmd FileType c,cpp,java,python,lua,html,css NeoBundleSource syntastic
	let g:syntastic_c_compiler = 'clang'
	let g:syntastic_cpp_compiler = 'clang++'
	let g:syntastic_cpp_compiler_options = '-std=c++11'

NeoBundle 'kien/ctrlp.vim'
	let g:ctrlp_map = '<c-p>'
	let g:ctrlp_cmd = 'CtrlP'
	let g:ctrlp_working_path_mode = 'ra'
	let g:ctrlp_custom_ignore = {
				\ 'dir':  '\v[\/]\.(git|hg|svn)$',
				\ 'file': '\v\.(exe|so|dll|swp|bak|pyc|class)$',
				\ }

	" Use Ag (silver searcher) if possible over default vim's globpath
	if executable('ag')
		let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
	endif

" NeoComplete requires vim to be compiled with lua support
if has('lua')
	NeoBundle 'Shougo/neocomplete.vim'

	let g:neocomplete#enable_at_startup = 1
	let g:neocomplete#enable_smart_case = 1
	let g:neocomplete#sources#syntax#min_keyword_length = 3

	let g:neocomplete#sources#dictionary#dictionaries = { 'default' : '' }
	if !exists('g:neocomplete#keyword_patterns')
		let g:neocomplete#keyword_patterns = {}
	endif

	" Allow only words to be in the keyword
	let g:neocomplete#keyword_patterns['default'] = '\h\w*'

	" Enable omni completion
	if !exists('g:neocomplete#force_omni_input_patterns')
	  let g:neocomplete#force_omni_input_patterns = {}
	endif

	let g:neocomplete#force_omni_input_patterns.c =
		\ '[^.[:digit:] *\t]\%(\.\|->\)\w*'
	let g:neocomplete#force_omni_input_patterns.cpp =
		\ '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'

	" Allow clang_complete and neocomplete to work together
	let g:neocomplete#force_overwrite_completefunc = 1
	let g:clang_complete_auto = 0
	let g:clang_auto_select = 0
	let g:clang_use_library = 1
endif

NeoBundleLazy 'Rip-Rip/clang_complete'
	autocmd FileType c,cpp NeoBundleSource clang_complete

NeoBundle 'godlygeek/tabular'
NeoBundle 'Raimondi/delimitMate'
NeoBundle 'w0ng/vim-hybrid'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'tpope/vim-surround'
NeoBundle 'tpope/vim-repeat'

NeoBundleCheck

" -----------------
" Personal Settings
" -----------------

filetype plugin indent on
syntax on

set encoding=utf-8

" Remap leader key from default backslash(\) to spacebar
let mapleader=" "

" Disable sounds
set noerrorbells
set novisualbell
set t_vb=

" Improves redrawing
set ttyfast

" Don't update screen while executing a macro, register or
" other commands that not have been typed
set lazyredraw

" Mouse
set mouse=a   " Enable Mouse
set mousehide " Hide mouse when typing

" Allows you to edit other files without saving current file
set hidden

" No backup files
set nobackup
set noswapfile

" Number of command lines to remember
set history=1000

" Allow to use backspace in insert mode
set backspace=indent,eol,start

" Adds line numbers to the left side of the editor
set number

" Adds column numbers to the bottom right of the editor
set ruler

" Highlight the line you are on
set cursorline

" Specific tabs, spaces and textwidth for certain file types
autocmd FileType html,css setlocal tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab
autocmd FileType java setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType c setlocal tabstop=8 softtabstop=8 shiftwidth=8 noexpandtab textwidth=80 equalprg=indent\ -kr\ -i8\ -l80
autocmd FileType cpp setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab textwidth=120

" Show tabs and end of line characters
set list
set listchars=tab:▸\ ,eol:¬

" Add a visual vertical line 1 column after textwidth
if exists('+colorcolumn')
	set colorcolumn=+1
endif

" Searching
set hlsearch   " Highlight search terms
set incsearch  " Show search matches as you type
set ignorecase " Case-Insensitive when searching
set smartcase  " Except if there's a capital letter

" Time it takes to update gui while not doing anything (milliseconds)
set updatetime=200

" Fixes delay after pressing ESC and then O
set timeout timeoutlen=1000 ttimeoutlen=100

" Fixes lag/delay when inserting parentheses and brackets in large files
let g:matchparen_insert_timeout=5

" Color Scheme
let g:hybrid_use_Xresources=1
colorscheme hybrid

" Enable command-line completion
set wildmenu
set wildignore+=*.swp,*.bak,*.pyc,*.class,*/.git/**/*,*/.hg/**/*,*/.svn/**/*,*/tmp/*,*.so
set wildignorecase
set wildmode=list:full

" Automatically remove trailing whitespace
autocmd FileType c,cpp,java,python,lua,vim,html,css autocmd BufWritePre <buffer> :%s/\s\+$//e

" Detect markdown files and set the correct filetype
au BufRead,BufNewFile *.md set filetype=markdown

" Map CTRL + L to clear highlighting and then clear/redraw screen.
nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
