#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%A, %B %d, %H:%M %P' > "$PANEL_FIFO" &
conky > "$PANEL_FIFO" &

. panel_colors

cat "$PANEL_FIFO" \
	| panel_bar \
	| bar \
		-g "x18+0+0"\
		-f "-benis-uushi-medium-r-normal--11-90-75-75-p-58-iso10646-1"\
		-u 1\
		-B "${COLOR_BACKGROUND}"\
		-F "${COLOR_FOREGROUND}" &

wait
