#! /bin/sh

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
xtitle -s -t 75 -f 'T%s' > "$PANEL_FIFO" &
# LC_TIME="ja_JP.UTF-8" clock -sf 'S%A、%x、%H:%M' > "$PANEL_FIFO" &
clock -sf 'S%A、%x、%H:%M' > "$PANEL_FIFO" &
conky > "$PANEL_FIFO" &

. panel_colors

cat "$PANEL_FIFO" \
	| panel_bar \
	| lemonbar \
		-n "$PANEL_WM_NAME"\
		-g "x20+0+0"\
		-f "Open Sans:size=10:style=Semibold:antialias=true"\
		-f "DejaVu Sans Mono:size=9:style=Book:antialias=true"\
		-f "Kozuka Gothic Pro:size=11:style=M:antialias=true"\
		-f "Baekmuk Gulim:size=11:style=Regular:antialias=true"\
		-u 2\
		-B "${COLOR_BACKGROUND}"\
		-F "${COLOR_FOREGROUND}" &

# Keep lemonbar on top so that windows can overlap it
wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
