#! /bin/sh

# ------------
# bspwm config
# ------------

bspc config top_padding           20
bspc config border_width          4
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus     true
bspc config click_to_focus        true

bspc config focused_border_color "#556699"
bspc config active_border_color "#556699"
bspc config normal_border_color "#2f3969"
bspc config presel_feedback_color "#2f3969"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# -----
# Rules
# -----
bspc rule -a Steam state=floating desktop=^9
bspc rule -a URxvt:ncmpcpp desktop=^8
bspc rule -a Mumble state=floating
bspc rule -a Gimp state=floating
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Thunar:thunar state=floating

# ------------------
# Autostart Programs
# ------------------
panel &
redshift -c ~/.config/redshift.conf &
urxvt -name ncmpcpp -e ncmpcpp &
steam &
