#! /bin/sh

# ------------
# bspwm config
# ------------
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config top_padding           18
bspc config border_width          2
bspc config window_gap            0
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

# -----
# Rules
# -----
bspc rule -a Steam -d 9 --floating
bspc rule -a ncmpcpp -d 8
bspc rule -a Mumble --floating
bspc rule -a gimp --floating
bspc rule -a feh --floating

# ------------------
# Autostart Programs
# ------------------
panel &
redshift -c ~/.config/redshift.conf &
steam &
urxvt -name ncmpcpp -e ncmpcpp &
