#! /bin/sh

# ------------
# bspwm config
# ------------

bspc config top_padding           48
bspc config border_width          4
bspc config window_gap            10
bspc config split_ratio           0.50
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus     true
bspc config click_to_focus        button1

bspc config focused_border_color "#665c54"
bspc config active_border_color "#665c54"
bspc config normal_border_color "#32302f"
bspc config presel_feedback_color "#32302f"

bspc monitor DVI-I-1 -d 一 二 三 四 五 六 七 八 九 十
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 0

# -----
# Rules
# -----
#bspc config external_rules_command "/home/an/.config/bspwm/external_rules"
bspc rule -a Steam state=floating desktop=^9
bspc rule -a ncmpcpp:ncmpcpp desktop=^8
bspc rule -a Mumble state=floating
bspc rule -a Gimp state=floating
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a Anki:anki state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Vmplayer:vmplayer state=floating
bspc rule -a pcsx2 state=floating
bspc rule -a Thunar:thunar state=floating

# ------------------
# Autostart Programs
# ------------------
synology-cloud-station-drive &
$HOME/.config/polybar/launch.sh
redshift -c ~/.config/redshift.conf &
termite --name="ncmpcpp" --class="ncmpcpp" -e ncmpcpp &
